sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t zajzajer/cli-hello-world -f Dockerfile.dev .

script:
    - docker run -e CI=true zajzajer/cli-hello-world npm run test -- --coverage